---
- name: Install and Configure Jenkins with Python Dependencies
  hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  vars:
    java_package: java-17-amazon-corretto-devel
    jenkins_repo_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    jenkins_key_url: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

  tasks:
    - name: Install OpenJDK 17
      dnf:
        name: "{{ java_package }}"
        state: present

    - name: Download Jenkins repository file
      get_url:
        url: "{{ jenkins_repo_url }}"
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      shell: rpm --import "{{ jenkins_key_url }}"

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins service on boot
      systemd:
        name: jenkins
        enabled: true

    - name: Ensure pip is installed for Python 3.11
      shell: python3.11 -m ensurepip --upgrade
      args:
        creates: /usr/local/bin/pip3.11

    - name: Upgrade pip for Python 3.11
      shell: python3.11 -m pip install --upgrade pip

    - name: Install setuptools for Python 3.11
      shell: python3.11 -m pip install setuptools

    - name: Install docker-py for Python 3.11
      shell: python3.11 -m pip install docker

    - name: Wait for Jenkins port 8080 to be available
      wait_for:
        port: 8080
        delay: 30
        state: started

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass

    - name: Display Jenkins admin password
      debug:
        var: jenkinspass.stdout